### ISSUE TITLE
Error when reproducing the "car" example

### ISSUE THREAD

**Issue by stla** [rcharts/parcoords#2]
Hello,

I'm trying to create the plots of the [car example](http://ramnathv.github.io/rChartsParCoords/).  

I run this code : 

```
cars <- read.csv('data/cars.csv')
p1 <- rCharts$new()
p1$field('lib', 'parcoords')
p1$set(padding = list(top = 24, left = 0, bottom = 12, right = 200))
p1$set(data = toJSONArray(cars, json = F), 
  colorby = 'economy', 
  range = range(cars$economy),
  colors = c('steelblue', 'brown')
)
p1$print('chart')
```

and then I get this error message : 

```

> p1$print('chart')
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/layouts/chart.html': No such file or directory
```

Is there something else to do ?

**Comment by stla** [comment]
Mmm it works when I set `rcharts-parcoords-997f882/libraries/widgets` as the working directory.

**Comment by ramnathv** [comment]
The reason it does not work is that the `parcoords` folder is not a part of the `libraries` in `rCharts`. Easiest fix is to refer to the correct path to the `parcoords` folder, when you do `p1$field('lib', 'path/to/parcoords')`.

I am thinking of packaging `parcoords` and other such libraries in a new package `rChartsExtra`.

**Comment by stla** [comment]
Yes, it works ! Thank you !!

**Comment by ramnathv** [comment]
Perfect.

**Comment by stla** [comment]
Ramnath, I have noticed some strange behavior, I don't know whether this is due to your package or to the Javascript library. I try to explain but this is difficult in English (even in French actually ;-) : when I exchange two vertical bars with the mouse, for instance "cylinders" and "displacement", the old lines are still visible (in light gray). Do you see what I mean ?

**Comment by ramnathv** [comment]
Can you post a short screencast of the behaviour you are experiencing? You can use http://www.screenr.com/ to quickly record and share. It would make it easier for me to understand what you are talking about.

**Comment by stla** [comment]
Actually this is easy to see with two static pictures.
Here is the original graphic : 
![noname1](https://f.cloud.github.com/assets/4466543/702936/f2fd6354-dd9f-11e2-9adb-2dee257a1ba9.png)
Focus on the  two first vertical bars (Group and Lot). The original graphic becomes the following one when I exchange these two bars : 
![noname2](https://f.cloud.github.com/assets/4466543/702949/2b976160-dda0-11e2-9d60-f49e9293d00f.png)
The lines joining Group to Lot in the original graphic are still visible on the second graphic. I think this is unexpected.

**Comment by foldager** [comment]
I have exactly the same problem as stla , but the solution does not work for me. Changing working directory to `bla/bla/libraries/widgets` does not work, and neither does setting `p1$field('lib', 'path/to/parcoords')`

I looked a bit at the structure of `p1` and I found this field:

```
> p1$templates[[3]]
[1] "/layouts/chart.html"
```

If I manually set it to the correct path, everything works. 

```
p1$templates[[3]] <- "/my/path/to/parcoords/layouts/chart.html"
```

Should I just stick to this solution? It seems like the wrong way to go about it?

**Comment by ramnathv** [comment]
There has been a lot of refactoring of `rCharts` that changed things. Can you try this and let me know if it works. This should automatically locate the library as well as set the templates correctly.

``` S
p1$setLib("path/to/parcoords")
```

**Comment by foldager** [comment]
Sorry, but it does not work for me. Here is how I did on my system:

```
> cars <- read.csv('data/cars.csv')
> p1 <- rCharts$new()
> p1$setLib("/Users/Jesper/Library/R/3.0/library/rCharts/parcoords")
> str(p1)
Reference class 'rCharts' [package "rCharts"] with 8 fields
 $ params   :List of 3
  ..$ dom   : chr "chart35ab33aa9bf2"
  ..$ width : num 800
  ..$ height: num 400
 $ lib      : chr "/Users/Jesper/Library/R/3.0/library/rCharts/parcoords"
 $ LIB      :List of 2
  ..$ name: chr "parcoords"
  ..$ url : chr "/Users/Jesper/Library/R/3.0/library/rCharts/parcoords"
 $ srccode  : NULL
 $ tObj     : list()
 $ container: chr "div"
 $ html_id  : chr ""
 $ templates:List of 3
  ..$ page    : chr "rChart.html"
  ..$ chartDiv: NULL
  ..$ script  : chr "/layouts/chart.html"
 and 24 methods, of which 12 are possibly relevant:
   addParams, getPayload, html, initialize, print, publish, render, save, set, setLib, setTemplate, show#envRefClass
> p1$set(padding = list(top = 24, left = 0, bottom = 12, right = 200))
> p1$set(data = toJSONArray(cars, json = F), 
+   colorby = 'economy', 
+   range = range(cars$economy),
+   colors = c('steelblue', 'brown')
+ )
> p1
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/layouts/chart.html': No such file or directory
> p1$templates[[3]] <- "/Users/Jesper/Library/R/3.0/library/rCharts/parcoords/layouts/chart.html"
> p1
> 
```

After the last p1, the graph pops up in my browser.

**Comment by ramnathv** [comment]
You need to update your installation of `rCharts`.

``` S
require(devtools)
install_github('rCharts', 'ramnathv', ref = 'dev')
```

Check by running

``` S
p1 <- rCharts$new()
p1$setLib(system.file('parcoords' , package = 'rCharts'))
p1$templates$script
```

If everything went well, you should see something like

```
/Users/Jesper/Library/R/3.0/library/rCharts/parcoords/layouts/chart.html
```

**Comment by foldager** [comment]
Thank you, now it works. I thought I was up to date with `install_github('rCharts', 'ramnathv')`.

**Comment by ramnathv** [comment]
We have a `dev` branch where we push the latest features. This will be merged back into the main master branch shortly.

**Comment by kundeng** [comment]
I have trouble reproducing http://ramnathv.github.io/rChartsParCoords/

I installed both rCharts and slidify and when I run slidify("index.Rmd"),
I got the following error:

``` S
output file: index.md

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'libraries/widgets/parcoords/parcoords.html': No such file or directory
```

This happened for both the main branch as well as the dev branch. 
In the main branch,  parcoords is directly under libraries. 
in the dev branch: there is not parcoords. 

Can someone tell me whether I am following the right workflow?

**Comment by ramnathv** [comment]
The reason for the error is that the `parcoords` library is no longer packaged with `rCharts`. I will be packaging such one-off libraries into `rChartsExtra`. But for now, your best bet is to manuall download the `rChartsParCoords` repo, and copy-paste the `libraries/widgets/parcoords` folder into your `libraries/widgets/parcoords` folder. 

Hope this helps.

**Comment by ramnathv** [comment]
Alternately, you can directly use the `parcoords` folder from my online repository. The following piece of code will give you a parallel coordinates plot, when run from the R console, assuming you have the dev branch of rCharts installed. To use within slidify, you can throw the same code into a code chunk, and slidify will automatically recognize that it is running within `knitr` and do the needful.

``` S
require(rCharts)
cars <- read.csv('http://ramnathv.github.io/rChartsParCoords/data/cars.csv')
p1 <- rCharts$new()
p1$setLib('http://ramnathv.github.io/rChartsParCoords/libraries/widgets/parcoords')
p1$set(padding = list(top = 24, left = 0, bottom = 12, right = 200))
p1$set(data = toJSONArray(cars, json = F), 
  colorby = 'economy', 
  range = range(cars$economy),
  colors = c('steelblue', 'brown')
)
p1
```

**Comment by kundeng** [comment]
I tried. Still complaining about the error. 

I'm confused about 2 things:
1.  under the R library folder D:\kundeng\Doc\R\win-library\3.0\rCharts, there is already a parcoords directory. I guess this one is outdated?
2.  When knitr does its thing,  Will it copy the necessary javascript and other things to the right location?  Or do I need to manually install some files under the example directory?  Under the example directory, 
D:/kundeng/rcharts-parcoords 

I have: 
assets/
data/
libraries/
    widgets/
    frameworks/
    ....
index.Rmd
...

**Comment by ramnathv** [comment]
Does the code I posted work for you (the one that reads data and sets the library path to the online http link)?

**Comment by kundeng** [comment]
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'libraries/widgets/parcoords/parcoords.html': No such file or directory

**Comment by kundeng** [comment]
Sorry, I still have no luck getting your examples working.  

All I want to do is something like this: 
I want to edit RMD file in Rstudio, then knitr or slidfy into a report.   I am practicing this with rCharts.  I can't even get a simple example like the following to work.  knitr works, but the generated report has javascript error. 

The iframe works, but the inline doesn't show.  The error in the Chrome's development console is:
Uncaught ReferenceError: $ is not defined  around:

$(document).ready(function(){
      drawchart8b013b71097()
    });

## NVD3 Plot Inline

``` r nvd3plot, results = 'asis', comment = NA, message = F, echo = F
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1$show('inline')
```

---

## NVD3 Plot Iframe

``` r nvd3plot2, results = 'asis', comment = NA, message = F, echo = F
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1
```

**Comment by kundeng** [comment]
It seems that the main html file forgets to include jquery libraries and so forth?  Am I totally confused about the usage of this package?

**Comment by ramnathv** [comment]
Okay, let us break this problem into two parts.
1. Getting the chart to work in your R Console.
2. Getting the chart to work in an Rmd document.

From your description, I am confused as to which part is giving you trouble.

If it is the Rmd part, then the `iframe` will work by default, the `inline` will work, but needs some additional metadata to be specified. 

I would recommend, you post a link to the exact code you tried so that I can figure out where you went wrong.

**Comment by kundeng** [comment]
ok. Thanks.  I am using Rstudio as my editor. 
1.  I can't get the chart to show IN Rstudio. It opens up a separate internet browser window and graph is shown correctly there.  I assume  this is the correct behavior?  
2.  I tried to get it to work in an Rmd document---> knitr ---> html report.  This is what is giving trouble. 

The document test1.Rmd is the following. 

``````
```{r nvd3plot, results = 'asis', comment = NA, message = F, echo = F}
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1$show('inline')
```
## NVD3 Plot Iframe

```{r nvd3plot2, results = 'asis', comment = NA, message = F, echo = F} 
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1
```
``````

What happens is that:
1. if I use the main branch, nothing is shown. 
2. if I use the dev branch, the iframe is shown, but not the inline.
